name: easyazz
favicon: null
layout_spectrum: 0.50349
typography_spectrum: 0.46792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1509'
    - '#a7da3e'
    - '#ffffff'
    - '#80a830'
    - '#43591c'
  brandStrength: 1
  lightness: 0
  saturation: 0.20466490811668336
  rhythmicContrast: 0.7832651974167675
purpose: []
