name: easyazz
favicon: null
layout_spectrum: 0.2129355848301202
typography_spectrum: 0.9679227871820331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6927948133088648
  lightness: 0.7092462512664497
  saturation: 0.20466490811668336
  rhythmicContrast: 0.7832651974167675
purpose: []
